version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress-stack-1
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER} 
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD} 
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - /home/docker/wordpress1:/var/www/html
    networks:
      - frontend
      - backend

  db:
    image: mysql:5.7
    restart: always
    container_name: wordpress-db-stack-1
    environment:
      MYSQL_DATABASE: ${DB_NAME} 
      MYSQL_USER: ${DB_USER} 
      MYSQL_PASSWORD: ${DB_PASSWORD} 
      MYSQL_RANDOM_ROOT_PASSWORD: ${DB_RANDOM_ROOT_PASSWORD}
    volumes:
      - /home/docker/wordpressdb1:/var/lib/mysql
    networks:
      - backend

   proxy:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    container_name: wordpress-proxy-stack-1
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /home/docker/nginx-proxy/data:/data
      - /home/docker/nginx-proxy/letsencrypt:/etc/letsencrypt
     networks:
      - backend
      
   watchtower:
    image: containrrr/watchtower
    hostname: "Summit-Heights-Preparatory-Website"
    container_name: wordpress-watchtower-stack-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATIONS: email 
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: ${EMAIL_FROM}
      WATCHTOWER_NOTIFICATION_EMAIL_TO: ${EMAIL_TO}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com 
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587 
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: ${EMAIL_USER}
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: ${APP_PASSWORD}
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2 
    networks:
      - frontend
      - backend
    command: --debug --cleanup --schedule "0 0 1 * * *"
    

networks:
  frontend:
    external: true
  backend:
    external: true
    
